version: "3.8"

services:
  app:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - files:/app/dist/public
      - /app/node_modules
      - ./backend:/app
    networks:
      - development
    env_file:
      - ./env/backend.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    networks:
      - development
    env_file:
      - ./env/postgres.env
    volumes:
      - mertion-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_db:/data
    networks:
      - development
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /web/node_modules
      - ./frontend:/web
    restart: always
    networks:
      - development
    depends_on:
      - app

volumes:
  redis_db:
  files:
  mertion-data:

networks:
  development:
