version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - /app/.env
      - .:/app
    environment:
      - ./.env
    networks:
      - host
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mert
  redis:
    image: redis
    restart: always
    volumes:
      - redis_db:/data
  web:
    build: /mnt/3822EF8822EF4988/projects-web/mertion/frontend/
    ports:
      - "3000:3000"
    volumes:
      - /web/node_modules
      - /mnt/3822EF8822EF4988/projects-web/mertion/frontend:/web
    depends_on:
      - app

volumes:
  redis_db:

networks:
  host:
