version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    # volumes:
    #   - .:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sellingpoint
  redis:
    image: redis
    volumes:
      - redis_db:/data

volumes:
  redis_db:
