version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sellingpoint

  redis:
    image: redis
    volumes:
      - redis_db:/data

volumes:
  redis_db:
