version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - files:/app/dist/public
      - /app/node_modules
      - .:/app
    networks:
      - development
    environment:
      - REDIS_URL=redis:6379
      - DATABASE_URL=postgres://mcuve:secret@postgres:5432/mertion
      - SESSION_SECRET=mysecret
      - PORT=4000
      - HOST_SERVER=http://localhost:4000/
      - ORIGIN=http://localhost:3000
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    networks:
      - development
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=mcuve
      - POSTGRES_DB=mertion
    volumes:
      - mertion-data=/var/lib/postgresql/data/pgdata
  redis:
    image: redis
    restart: always
    volumes:
      - redis_db:/data
    networks:
      - development
  web:
    build: ../frontend/
    ports:
      - "3000:3000"
    volumes:
      - /web/node_modules
      - ../frontend:/web
    networks:
      - development
    depends_on:
      - app

volumes:
  redis_db:
  files:
  mertion-data:

networks:
  development:
